background                = "#1a171d"
background-alpha          = 0.92
text                      = "#e9ecf2"
border                    = "hyprland.active-border"
border-alpha              = 0.92
border-width              = 2
scrim                     = "#050507"
scrim-alpha               = 0.22
selected-background       = "#c8c8df"
selected-background-alpha = 0.14
selected-text             = "#ffffff"
selected-border           = "#ff7447"
selected-border-alpha     = 0.72
selected-border-width     = 1
